version: '3.8'
services:
    mysql:
        image: mysql:5.7
        restart: on-failure
        environment:
            MYSQL_DATABASE: db_frenchfounders
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    
    phpmyadmin:
        image: phpmyadmin
        restart: on-failure
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
    
    nginx:
        image: nginx:1.19.0-alpine
        restart: on-failure
        volumes:
            - './public/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - 80:80
        depends_on:
            - php
    
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './:/usr/src/app'
        restart: on-failure
        env_file:
            - .env
        user: 1000:1000
        environment:
            DATABASE_URL: mysql://root:@mysql:3306/db_frenchfounders?serverVersion=5.7
            MAILER_URL: smtp://mailer:1025
            SLACK_WEBHOOK_ENDPOINT: https://hooks.slack.com/services/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
    
    mailer:
        image: maildev/maildev
        ports:
            - 1080:1080
            - 1025
        